apiVersion: v2
name: prometheus
version: 1.0.0
dependencies:
  - name: prometheus
    version: 25.8.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: volsync-app
    version: 1.0.0
    repository: "file://../volsync-app"

